{0.0.0.1} CONTINUE;
NORMAL[0,bin/rfspa.exe,app.exe]0.0.0.0;
NORMAL[1,bin/rfspa.exe.config,app.exe.config]0.0.0.0;
NORMAL[2,lib/dtsvc.dll,lib/dtsvc.dll]0.0.0.0;
NORMAL[3,lib/Newtonsoft.Json.dll,lib/Newtonsoft.Json.dll]0.0.0.0;
NORMAL[4,lib/Newtonsoft.Json.xml,lib/Newtonsoft.Json.xml]0.0.0.0;
NORMAL[5,lib/objlib.dll,lib/objlib.dll]0.0.0.0;
DELETE[6,lib/sndlib.dll,lib/sndlib.dll];
NORMAL[7,lib/System.Net.Http.Formatting.dll,lib/System.Net.Http.Formatting.dll]0.0.0.0;
NORMAL[8,lib/System.Net.Http.Formatting.xml,lib/System.Net.Http.Formatting.xml]0.0.0.0;
NORMAL[9,lib/Test_Configurations.dll,lib/Test_Configurations.dll]0.0.0.0;
